#!/usr/bin/env bash

# Find the process ID (PID) of the '4-to_infinity_and_beyond' process
PID=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$PID" ]; then
  echo "Process '4-to_infinity_and_beyond' is not running."
else
  # Terminate the process using the PID
  kill "$PID"
  echo "Process '4-to_infinity_and_beyond' terminated."
fi
