#!/usr/bin/env bash
#display
prog_pid=()
readarray -t prog_pid < < (preg -la -x ".bash*" | grep '4-to_infinity_and_beyond | cut 'I' -f 1 for ((i = 0; i < "${#prog_pid[@]}"; i++)) do
      kill -s SIGTERM "${prog_pid[1]}"
done       
